name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push image
      uses: azure/acr-build@v1
      with:
        registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        image: springboot-config:v1
        dockerfile: Dockerfile
        branch: main
